sonata_media:
    db_driver: doctrine_orm
    default_context: default
    class:
        media: App\Application\Sonata\MediaBundle\Entity\Media
        gallery: App\Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media: App\Application\Sonata\MediaBundle\Entity\GalleryHasMedia
        category: App\Application\Sonata\ClassificationBundle\Entity\Category

    contexts:
#        default:
#            providers:
#                - sonata.media.provider.dailymotion
#                - sonata.media.provider.youtube
#                - sonata.media.provider.image
#                - sonata.media.provider.file
#                - sonata.media.provider.vimeo
#
#            formats:
#                small: { width: 100 , quality: 70}
#                big:   { width: 500 , quality: 70}

        news:
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.vimeo

            formats:
                w100:  { width: 100,  quality: 80}
                w200:  { width: 200,  quality: 80}
                w500:  { width: 500,  quality: 80}
                w800:  { width: 800,  quality: 80}
                w1000: { width: 1000, quality: 80}
                w1500: { width: 1500, quality: 80}

    cdn:
        server:
            path: /upload/media

    filesystem:
        local:
            # Directory for uploads should be writable
            directory: "%kernel.project_dir%/public/upload/media"
            create: false8

#
#sonata_media:
#    # if you don't use default namespace configuration
#    #class:
#    #    media: MyVendor\MediaBundle\Entity\Media
#    #    gallery: MyVendor\MediaBundle\Entity\Gallery
#    #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
#    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
#    default_context: default # you need to set a context
#    contexts:
#        default:  # the default context is mandatory
#            providers:
#                - sonata.media.provider.dailymotion
#                - sonata.media.provider.youtube
#                - sonata.media.provider.image
#                - sonata.media.provider.file
#                - sonata.media.provider.vimeo
#
#            formats:
#                small: { width: 100 , quality: 70}
#                big:   { width: 500 , quality: 70}
#
#    cdn:
#        server:
#            path: /uploads/media # http://media.sonata-project.org/
#
#    filesystem:
#        local:
#            directory:  "%kernel.root_dir%/../public/uploads/media" #flex
#            #directory:  "%kernel.root_dir%/../web/uploads/media" #non-flex
#            create:     false