sonata_seo:
  encoding:         UTF-8
  page:
    title: Открытая жизнь.
    default:          sonata.seo.page.default
    metas:
      name:
        keywords: Свингерство, свинг, секс, групповой секс, любовь, парные отношения, секусуальность
        description: Блог об открытых отношения, свинг встречах и путешествиях.
        robots: index, follow

      property:
        # Facebook application settings
        #'fb:app_id':          XXXXXX
        #'fb:admins':          admin1, admin2

        # Open Graph information
        # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
        'og:site_name': "Блог Открытая Жизнь"
        'og:description': "Блог об открытых отношениях, свингерстве и секусуальности"

      http-equiv:
        'Content-Type':         text/html; charset=utf-8
        #'X-Ua-Compatible':      IE=EmulateIE7

      charset:
        UTF-8:    ''

    head:
      'xmlns':              http://www.w3.org/1999/xhtml
      'xmlns:og':           http://opengraphprotocol.org/schema/
      #'xmlns:fb':           "http://www.facebook.com/2008/fbml"